"""SymbiYosys formal hooks (FV-1, FV-2).

Generates a formal wrapper asserting that valid_N is exactly the computed
critical-path delay of valid_0, plus optional no-overflow assumptions from
RP-1 input ranges, and a .sby project file. Yosys/sby absence disables the
feature with an actionable message (C2/FV-2).
"""

from __future__ import annotations

import shutil
from pathlib import Path

from pipeforge.core.audit.engine import Audit
from pipeforge.core.ranges.interval import Interval


class FormalUnavailable(RuntimeError):
    pass


def check_formal_tools() -> None:
    missing = [name for name in ("yosys", "sby") if shutil.which(name) is None]
    if missing:
        raise FormalUnavailable(
            "Formal verification needs "
            + " and ".join(missing)
            + " (install Yosys/SymbiYosys). Everything else keeps working without them."
        )


def render_formal_wrapper(
    audit: Audit,
    dut_module: str,
    input_ranges: dict[str, Interval] | None = None,
) -> str:
    """SVA wrapper: assert valid-propagation delay == computed latency (FV-1)."""
    cm = audit.cm
    latency = audit.total_latency
    inputs = [n.label for n in audit.dag.inputs()]
    in_ports = "\n".join(f"  input [{cm.width - 1}:0] {name}_0," for name in inputs)
    outputs = [n.signal for n in audit.dag.outputs() if n.signal]
    out_decls = "\n".join(f"wire [{cm.width - 1}:0] {name}_N;" for name in outputs)
    out_conns = ",\n".join(f"    .{name}_N ({name}_N)" for name in outputs)
    in_conns = ",\n".join(f"    .{name}_0 ({name}_0)" for name in inputs)
    assumes = []
    if input_ranges:
        for name, iv in input_ranges.items():
            lo = int(iv.lo * (1 << cm.scale))
            hi = int(iv.hi * (1 << cm.scale))
            assumes.append(
                f"  assume property (@(posedge clk) "
                f"$signed({name}_0) >= {lo} && $signed({name}_0) <= {hi});"
            )
    assume_block = "\n".join(assumes)
    return f"""// generated by pipeforge formal — do not edit
module formal_top
  (
  input clk,
  input reset,
  input valid_0,
{in_ports}
  input unused_tieoff
  );

fixedp #(.WIDTH({cm.width}), .SCALE({cm.scale})) g (.clk (clk), .reset (reset));

wire valid_N;
{out_decls}

{dut_module} i_dut
  (
    .g (g),
    .valid_0 (valid_0),
{in_conns},
    .valid_N (valid_N),
{out_conns}
  );

// reference model of the valid chain: a {latency}-deep shift register
reg [{max(latency - 1, 0)}:0] valid_ref;
always @(posedge clk)
  if (reset)
    valid_ref <= '0;
  else
    valid_ref <= {{ valid_ref[{max(latency - 2, 0)}:0], valid_0 }};

// FV-1: valid propagation equals the cost-model latency ({latency} cycles)
always @(posedge clk)
  if (!reset)
    assert (valid_N == valid_ref[{max(latency - 1, 0)}]);

{assume_block}

endmodule
"""


def render_sby(sources: list[str], include_dir: str, depth: int = 64, mode: str = "bmc") -> str:
    files = "\n".join(sources)
    return f"""[options]
mode {mode}
depth {depth}

[engines]
smtbmc

[script]
read -formal -I{include_dir} {" ".join(Path(s).name for s in sources)}
prep -top formal_top

[files]
{files}
"""


def write_formal_project(
    audit: Audit,
    dut_sv: Path,
    dut_module: str,
    work_dir: Path,
    extra_sources: list[Path] | None = None,
    include_dir: Path | None = None,
    input_ranges: dict[str, Interval] | None = None,
) -> Path:
    """Write formal_top.sv + project.sby; returns the .sby path (FV-1)."""
    work_dir.mkdir(parents=True, exist_ok=True)
    wrapper = work_dir / "formal_top.sv"
    wrapper.write_text(render_formal_wrapper(audit, dut_module, input_ranges), encoding="utf-8")
    sources = [str(wrapper), str(dut_sv), *[str(s) for s in (extra_sources or [])]]
    sby = work_dir / "project.sby"
    sby.write_text(render_sby(sources, str(include_dir) if include_dir else "."), encoding="utf-8")
    return sby
