"""Co-simulation harness generation (CS-1b/c).

Generates, into a working directory:
  * ``tb_wrapper.sv``  — instantiates ``fixedp`` and the DUT with plain ports
  * ``tb_cosim.py``    — cocotb testbench: drives valid-paced stimulus,
                          collects valid-gated outputs, writes actual.json
  * ``stimulus.json``  — input vectors (raw bit patterns)
  * ``expected.json``  — golden-model outputs + the cost-model latency
The comparison (RTL == golden, bit-for-bit, cycle-aligned) happens host-side
in :mod:`pipeforge.core.cosim.runner`.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from pipeforge.core.audit.engine import Audit
from pipeforge.core.cosim.stimulus import Vector
from pipeforge.core.fxp.evaluator import evaluate_fixed
from pipeforge.core.fxp.fx import FxFormat


@dataclass(frozen=True)
class HarnessSpec:
    dut_module: str
    inputs: list[str]  # port base names (RTL ports are <name>_0)
    outputs: list[str]  # compared output base names (RTL ports are <name>_N)
    width: int
    scale: int
    latency: int  # cost-model critical path: first valid_N delay
    probes: list[str] = field(default_factory=list)  # captured-only ports (CS-7)


def harness_spec(audit: Audit, dut_module: str, probes: list[str] | None = None) -> HarnessSpec:
    dag = audit.dag
    inputs = [n.label for n in dag.inputs()]
    outputs = [n.signal for n in dag.outputs() if n.signal]
    return HarnessSpec(
        dut_module=dut_module,
        inputs=inputs,
        outputs=outputs,
        width=audit.cm.width,
        scale=audit.cm.scale,
        latency=audit.total_latency,
        probes=probes or [],
    )


def golden_outputs(audit: Audit, vectors: list[Vector], fmt: FxFormat) -> dict[str, list[int]]:
    """Golden-model output streams, keyed by output name (CS-1c reference)."""
    outs: dict[str, list[int]] = {}
    out_nodes = {n.signal: n.nid for n in audit.dag.outputs() if n.signal}
    for vec in vectors:
        values = evaluate_fixed(audit.dag, dict(vec.items()), fmt)
        for name, nid in out_nodes.items():
            outs.setdefault(name, []).append(values[nid][0])
    return outs


def render_wrapper_sv(spec: HarnessSpec) -> str:
    """Plain-port wrapper so cocotb need not drive a SystemVerilog interface."""
    sampled = spec.outputs + spec.probes  # probes are extra valid-gated outputs
    in_ports = "\n".join(f"  input  [{spec.width - 1}:0] {name}_0," for name in spec.inputs)
    out_ports = "\n".join(f"  output [{spec.width - 1}:0] {name}_N," for name in sampled)
    in_conns = ",\n".join(f"    .{name}_0 ({name}_0)" for name in spec.inputs)
    out_conns = ",\n".join(f"    .{name}_N ({name}_N)" for name in sampled)
    return f"""// generated by pipeforge cosim — do not edit
module tb_wrapper
  (
  input  clk,
  input  reset,
  input  valid_0,
{in_ports}
  output valid_N,
{out_ports}
  output dummy_unused
  );

fixedp #(.WIDTH({spec.width}), .SCALE({spec.scale})) g (.clk (clk), .reset (reset));

{spec.dut_module} i_dut
  (
    .g (g),
    .valid_0 (valid_0),
{in_conns},
    .valid_N (valid_N),
{out_conns}
  );

assign dummy_unused = 1'b0;

endmodule
"""


def render_cocotb_tb(spec: HarnessSpec) -> str:
    """cocotb testbench: valid-paced driving, valid-gated capture (CS-1b)."""
    return f'''"""generated by pipeforge cosim — do not edit"""
import json
import os

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge

INPUTS = {spec.inputs!r}
OUTPUTS = {spec.outputs!r}
PROBES = {spec.probes!r}
SAMPLED = OUTPUTS + PROBES
LATENCY = {spec.latency}


@cocotb.test()
async def cosim(dut):
    work = os.environ["PIPEFORGE_COSIM_DIR"]
    with open(os.path.join(work, "stimulus.json")) as fh:
        stim_doc = json.load(fh)
    vectors = stim_doc["vectors"]
    schedule = stim_doc.get("valid_schedule") or None

    cocotb.start_soon(Clock(dut.clk, 10, units="ns").start())
    dut.reset.value = 1
    dut.valid_0.value = 0
    for name in INPUTS:
        getattr(dut, name + "_0").value = 0
    for _ in range(4):
        await RisingEdge(dut.clk)
    dut.reset.value = 0
    await RisingEdge(dut.clk)

    actual = {{name: [] for name in SAMPLED}}
    first_valid_cycle = None
    cycle = 0
    fed = 0
    total = len(vectors)
    # CS-6: a per-cycle valid schedule (True = present next vector; False = bubble),
    # then a drain tail. Comparison stays valid-gated regardless of cadence.
    drive_plan = list(schedule or [True] * total) + [False] * (LATENCY + 64)
    for drive in drive_plan:
        if len(actual[OUTPUTS[0]]) >= total:
            break
        if drive and fed < total:
            dut.valid_0.value = 1
            for name in INPUTS:
                getattr(dut, name + "_0").value = vectors[fed][name]
            fed += 1
        else:
            dut.valid_0.value = 0
        await RisingEdge(dut.clk)
        cycle += 1
        if dut.valid_N.value.is_resolvable and int(dut.valid_N.value):
            if first_valid_cycle is None:
                first_valid_cycle = cycle
            for name in SAMPLED:
                actual[name].append(int(getattr(dut, name + "_N").value))

    with open(os.path.join(work, "actual.json"), "w") as fh:
        json.dump(
            {{"outputs": actual, "first_valid_cycle": first_valid_cycle}}, fh
        )
'''


def render_native_tb(spec: HarnessSpec) -> str:
    """A self-driving SystemVerilog testbench for the Verilator-native backend.

    No cocotb, no C++: it reads stimulus.txt, drives valid-paced vectors, and
    writes valid-gated outputs to actual.txt — the same protocol as the cocotb
    path, so results are bit-identical (TL-1).
    """
    w = spec.width
    in_decls = "\n".join(f"  logic [{w - 1}:0] {n}_0;" for n in spec.inputs)
    out_decls = "\n".join(f"  logic [{w - 1}:0] {n}_N;" for n in spec.outputs)
    in_conns = ",\n".join(f"    .{n}_0 ({n}_0)" for n in spec.inputs)
    out_conns = ",\n".join(f"    .{n}_N ({n}_N)" for n in spec.outputs)
    in_fmt = " ".join("%d" for _ in spec.inputs)
    in_args = ", ".join(f"{n}_0" for n in spec.inputs)
    out_fmt = " ".join("%0d" for _ in spec.outputs)
    out_args = ", ".join(f"{n}_N" for n in spec.outputs)
    return f"""// generated by pipeforge cosim (verilator-native) — do not edit
`include "macros.svh"
module tb_native;
  logic clk = 0, reset = 1, valid_0 = 0, valid_N;
{in_decls}
{out_decls}
  fixedp #(.WIDTH({w}), .SCALE({spec.scale})) g (.clk (clk), .reset (reset));
  {spec.dut_module} i_dut
    (
      .g (g),
      .valid_0 (valid_0),
{in_conns},
      .valid_N (valid_N),
{out_conns}
    );
  always #5 clk = ~clk;
  integer fin, fout, code, total, fed, collected, cyc;
  initial begin
    fin = $fopen("stimulus.txt", "r");
    fout = $fopen("actual.txt", "w");
    code = $fscanf(fin, "%d\\n", total);
    repeat (4) @(posedge clk);
    reset = 0;
    fed = 0; collected = 0; cyc = 0;
    while (collected < total && cyc < total + {spec.latency} + 64) begin
      if (fed < total) begin
        valid_0 = 1;
        code = $fscanf(fin, "{in_fmt}\\n", {in_args});
        fed = fed + 1;
      end else begin
        valid_0 = 0;
      end
      @(posedge clk);
      cyc = cyc + 1;
      if (valid_N) begin
        $fwrite(fout, "{out_fmt}\\n", {out_args});
        collected = collected + 1;
      end
    end
    $fclose(fin);
    $fclose(fout);
    $finish;
  end
endmodule
"""


def write_native_collateral(
    audit: Audit, dut_module: str, vectors: list[Vector], work_dir: Path
) -> HarnessSpec:
    """Write the native testbench + plain stimulus/expected for TL-1."""
    fmt = FxFormat(audit.cm.width, audit.cm.scale)
    spec = harness_spec(audit, dut_module)
    work_dir.mkdir(parents=True, exist_ok=True)
    (work_dir / "tb_native.sv").write_text(render_native_tb(spec), encoding="utf-8")
    lines = [str(len(vectors))]
    lines += [" ".join(str(vec[n]) for n in spec.inputs) for vec in vectors]
    (work_dir / "stimulus.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
    expected = golden_outputs(audit, vectors, fmt)
    (work_dir / "expected.json").write_text(
        json.dumps({"outputs": expected, "latency": spec.latency}, indent=1), encoding="utf-8"
    )
    return spec


def write_harness(
    audit: Audit,
    dut_module: str,
    vectors: list[Vector],
    work_dir: Path,
    cadence: str = "continuous",
    probes: list[str] | None = None,
) -> HarnessSpec:
    """Write all generated collateral into work_dir (CS-1, CS-6, CS-7)."""
    from pipeforge.core.cosim.stimulus import valid_schedule

    fmt = FxFormat(audit.cm.width, audit.cm.scale)
    spec = harness_spec(audit, dut_module, probes=probes)
    work_dir.mkdir(parents=True, exist_ok=True)
    schedule = valid_schedule(len(vectors), cadence)
    (work_dir / "tb_wrapper.sv").write_text(render_wrapper_sv(spec), encoding="utf-8")
    (work_dir / "tb_cosim.py").write_text(render_cocotb_tb(spec), encoding="utf-8")
    (work_dir / "stimulus.json").write_text(
        json.dumps(
            {
                "vectors": vectors,
                "width": spec.width,
                "scale": spec.scale,
                "valid_schedule": schedule,
            },
            indent=1,
        ),
        encoding="utf-8",
    )
    expected = golden_outputs(audit, vectors, fmt)
    (work_dir / "expected.json").write_text(
        json.dumps({"outputs": expected, "latency": spec.latency}, indent=1),
        encoding="utf-8",
    )
    return spec
