"""Ground-truth datapath oracle from extracted I/O vectors (WS-5).

The `.mat` workspace carries input/output **test vectors** that are external
ground truth, independent of PipeForge's own golden model. This drives those
inputs through the (bit-exact) golden model and compares the result against the
reference outputs.

The honest bit-exactness rule (§10, the dominant correctness risk in this
family): the `.mat` output vectors are ``quantize(float_math(...))`` whereas the
golden model is ``fixedpoint_math(quantize(inputs))``. These agree only within
SQNR for **float** references. So:

  * a reference declared **fixed-point-generated** may be compared bit-for-bit;
  * a **float** reference is reported as an FX-4 within-precision result
    (max-abs / RMS / SQNR) and a bit-exact verdict is **never** claimed.

The active oracle mode is always reported.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from pipeforge.core.audit.engine import Audit
from pipeforge.core.cosim.stimulus import Vector
from pipeforge.core.fxp.evaluator import ErrorStats, error_stats, evaluate_fixed
from pipeforge.core.fxp.fx import FxFormat, from_float, to_float

REFERENCE_FIXED = "fixed"  # reference outputs were generated by fixed-point math
REFERENCE_FLOAT = "float"  # reference outputs are quantize(float_math(...))

MODE_BIT_EXACT = "bit-exact"
MODE_WITHIN_PRECISION = "within-precision"


@dataclass
class OracleResult:
    reference_kind: str
    mode: str
    outputs: dict[str, ErrorStats] = field(default_factory=dict)
    #: per-output bit-exactness — meaningful ONLY when reference_kind == fixed
    bit_exact: dict[str, bool] = field(default_factory=dict)

    @property
    def passed(self) -> bool | None:
        """Bit-exact pass/fail, or None for a within-precision (float) run.

        None is deliberate: against a float reference there is no bit-exact
        verdict to give.
        """
        if self.reference_kind != REFERENCE_FIXED:
            return None
        return all(self.bit_exact.values()) if self.bit_exact else None


def oracle_stimulus(inputs: dict[str, list[float]], fmt: FxFormat) -> list[Vector]:
    """Raw co-sim stimulus from the ground-truth input streams (WS-5).

    These drive the DUT instead of (or alongside) synthetic vectors; lane i
    takes element i of each stream.
    """
    lanes = max((len(v) for v in inputs.values()), default=0)
    return [
        {name: from_float(stream[i % len(stream)], fmt) for name, stream in inputs.items()}
        for i in range(lanes)
    ]


def run_vector_oracle(
    audit: Audit,
    inputs: dict[str, list[float]],
    references: dict[str, list[float]],
    fmt: FxFormat,
    reference_kind: str = REFERENCE_FLOAT,
) -> OracleResult:
    """Drive the golden model with ground-truth inputs and grade against refs.

    `inputs` maps each MATLAB input label to its value stream; `references` maps
    each output signal to its reference output stream. The comparison mode is
    gated on `reference_kind` (WS-5).
    """
    if reference_kind not in (REFERENCE_FIXED, REFERENCE_FLOAT):
        raise ValueError(f"unknown reference kind {reference_kind!r}")
    mode = MODE_BIT_EXACT if reference_kind == REFERENCE_FIXED else MODE_WITHIN_PRECISION

    out_nodes = {n.signal: n.nid for n in audit.dag.outputs() if n.signal}
    lanes = max((len(v) for v in inputs.values()), default=0)

    golden_float: dict[str, list[float]] = {sig: [] for sig in out_nodes}
    golden_raw: dict[str, list[int]] = {sig: [] for sig in out_nodes}
    for i in range(lanes):
        vec = {name: from_float(stream[i % len(stream)], fmt) for name, stream in inputs.items()}
        values = evaluate_fixed(audit.dag, dict(vec.items()), fmt)
        for sig, nid in out_nodes.items():
            golden_raw[sig].append(values[nid][0])
            golden_float[sig].append(to_float(values[nid][0], fmt))

    result = OracleResult(reference_kind=reference_kind, mode=mode)
    for sig, ref_stream in references.items():
        if sig not in out_nodes:
            continue
        n = min(len(ref_stream), lanes)
        ref = ref_stream[:n]
        result.outputs[sig] = error_stats(ref, golden_float[sig][:n])
        if reference_kind == REFERENCE_FIXED:
            # a fixed-generated reference must match the model bit-for-bit
            result.bit_exact[sig] = all(
                from_float(ref[i], fmt) == golden_raw[sig][i] for i in range(n)
            )
    return result
