"""Failing-vector persistence, replay, and testbench export (VX-1, VX-2).

Reproducibility is the currency of RTL debug: a failing co-sim run persists
its exact stimulus (``failure.json``) so `cosim --replay` re-runs precisely
those vectors, and any vector set exports as `$readmemh` hex files plus a
standalone self-checking SystemVerilog testbench that re-runs the same
comparison in Questa/Vivado/Verilator without PipeForge installed.
"""

from __future__ import annotations

import json
from pathlib import Path

from pipeforge.core.audit.engine import Audit
from pipeforge.core.cosim.stimulus import Vector

FAILURE_FILE = "failure.json"


def save_failure(
    work_dir: Path,
    vectors: list[Vector],
    inputs: list[str],
    failing_indexes: dict[str, int],
    width: int,
    scale: int,
) -> Path:
    """Persist the exact stimulus of a failing run for later replay (VX-1)."""
    payload = {
        "width": width,
        "scale": scale,
        "inputs": inputs,
        "first_failure_by_output": failing_indexes,
        "vectors": vectors,
    }
    out = work_dir / FAILURE_FILE
    work_dir.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, indent=1), encoding="utf-8")
    return out


def load_vectors(path: Path) -> list[Vector]:
    """Load a replay file written by save_failure (VX-1)."""
    doc = json.loads(path.read_text(encoding="utf-8"))
    vectors = doc.get("vectors")
    if not isinstance(vectors, list):
        raise ValueError(f"{path}: no 'vectors' array")
    return [{str(k): int(v) for k, v in vec.items()} for vec in vectors]


def export_testbench(
    audit: Audit,
    vectors: list[Vector],
    out_dir: Path,
    dut_module: str,
) -> list[Path]:
    """Write hex vectors + a standalone self-checking SV testbench (VX-2).

    Produces, in out_dir:
      * ``stim_<input>.hex``     — one hex word per vector, per input
      * ``expected_<output>.hex`` — golden-model outputs, per output
      * ``tb_check.sv``           — drives continuously, compares after the
                                    cost-model latency, prints PASS/FAIL and
                                    exits nonzero on mismatch
    The testbench needs only the DUT sources and nkMatlib — not PipeForge.
    """
    from pipeforge.core.cosim.harness import golden_outputs
    from pipeforge.core.frontend.dag import port_name
    from pipeforge.core.fxp.fx import FxFormat

    fmt = FxFormat(audit.cm.width, audit.cm.scale)
    inputs = [n.label for n in audit.dag.inputs()]
    outputs = [n.signal for n in audit.dag.outputs() if n.signal]
    expected = golden_outputs(audit, vectors, fmt)
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    digits = (audit.cm.width + 3) // 4
    for name in inputs:
        p = out_dir / f"stim_{port_name(name)}.hex"
        p.write_text("\n".join(f"{vec[name]:0{digits}x}" for vec in vectors), encoding="utf-8")
        written.append(p)
    for name in outputs:
        p = out_dir / f"expected_{name}.hex"
        p.write_text("\n".join(f"{v:0{digits}x}" for v in expected[name]), encoding="utf-8")
        written.append(p)
    tb = out_dir / "tb_check.sv"
    tb.write_text(render_check_tb(audit, dut_module, len(vectors)), encoding="utf-8")
    written.append(tb)
    return written


def render_check_tb(audit: Audit, dut_module: str, count: int) -> str:
    """The standalone self-checking testbench source (VX-2)."""
    w = audit.cm.width
    scale = audit.cm.scale
    from pipeforge.core.frontend.dag import port_name

    latency = audit.total_latency
    inputs = [port_name(n.label) for n in audit.dag.inputs()]
    outputs = [n.signal for n in audit.dag.outputs() if n.signal]
    in_decls = "\n".join(f"  logic [{w - 1}:0] {n}_0;" for n in inputs)
    out_decls = "\n".join(f"  logic [{w - 1}:0] {n}_N;" for n in outputs)
    mem_decls = "\n".join(f"  logic [{w - 1}:0] stim_{n} [0:{count - 1}];" for n in inputs)
    mem_decls += "\n" + "\n".join(
        f"  logic [{w - 1}:0] expected_{n} [0:{count - 1}];" for n in outputs
    )
    reads = "\n".join(f'    $readmemh("stim_{n}.hex", stim_{n});' for n in inputs)
    reads += "\n" + "\n".join(f'    $readmemh("expected_{n}.hex", expected_{n});' for n in outputs)
    in_conns = ",\n".join(f"    .{n}_0 ({n}_0)" for n in inputs)
    out_conns = ",\n".join(f"    .{n}_N ({n}_N)" for n in outputs)
    drives = "\n".join(f"        {n}_0 = stim_{n}[fed];" for n in inputs)
    checks = "\n".join(
        f"""        if ({n}_N !== expected_{n}[collected]) begin
          $display("FAIL: output {n} vector %0d: expected %h got %h",
                   collected, expected_{n}[collected], {n}_N);
          errors = errors + 1;
        end"""
        for n in outputs
    )
    return f"""// Generated by PipeForge (export-tb) — standalone self-checking testbench.
// Needs only the DUT + nkMatlib sources; PASS/FAIL on stdout, nonzero exit on FAIL.
`include "macros.svh"
module tb_check;
  logic clk = 0, reset = 1, valid_0 = 0, valid_N;
{in_decls}
{out_decls}
{mem_decls}
  integer fed, collected, errors, cyc;
  fixedp #(.WIDTH({w}), .SCALE({scale})) g (.clk (clk), .reset (reset));
  {dut_module} i_dut
    (
      .g (g),
      .valid_0 (valid_0),
{in_conns},
      .valid_N (valid_N),
{out_conns}
    );
  always #5 clk = ~clk;
  initial begin
{reads}
    errors = 0;
    repeat (4) @(posedge clk);
    reset = 0;
    @(posedge clk); // settle: piperam write-enable asserts one edge after reset
    fed = 0; collected = 0; cyc = 0;
    while (collected < {count} && cyc < {count} + {latency} + 64) begin
      if (fed < {count}) begin
        valid_0 = 1;
{drives}
        fed = fed + 1;
      end else begin
        valid_0 = 0;
      end
      @(posedge clk);
      cyc = cyc + 1;
      if (valid_N) begin
{checks}
        collected = collected + 1;
      end
    end
    if (collected < {count}) begin
      $display("FAIL: only %0d of {count} outputs seen (latency/valid-chain bug?)", collected);
      errors = errors + 1;
    end
    if (errors == 0) $display("PASS: {count} vectors bit-exact");
    else $display("FAIL: %0d mismatching comparison(s)", errors);
    if (errors != 0) $fatal(1);
    $finish;
  end
endmodule
"""
