"""Persistent (warm) MATLAB session — near-instant snapshots.

One MATLAB process stays alive inside the container, serving snapshot
requests over file-based RPC in ``config_dir()/matlab_session/`` (home is
shared with the container, so this needs no extra plumbing — and *any*
PipeForge process, GUI or CLI, can use a live server, not just the one that
started it). The cold start is paid once; after that a snapshot takes well
under a second, which is what makes file-watching auto-sync viable.

Note: a warm session holds a MATLAB license seat while it runs.
"""

from __future__ import annotations

import contextlib
import json
import secrets
import subprocess
import time
from collections.abc import Callable
from pathlib import Path

from pipeforge.core.frontend.varinfo import WorkspaceSnapshot
from pipeforge.paths import config_dir
from pipeforge.services.matlab_bridge import (
    MatlabConfig,
    MatlabUnavailable,
    _mq,
    fast_available,
    render_snapshot_function,
)

#: heartbeat younger than this means a server is alive. The server beats ~2 s
#: when idle, but it is single-threaded: during a snapshot it cannot beat, so
#: this window must comfortably exceed a normal snapshot or a *busy* server gets
#: misread as dead (callers then spawn a redundant batch MATLAB). A truly dead
#: server is still caught — the request itself times out and falls back.
HEARTBEAT_FRESH_S = 15.0
#: budget for the one-time cold start of the server
START_TIMEOUT_S = 180.0
#: budget for a single warm snapshot request
REQUEST_TIMEOUT_S = 30.0


def session_dir() -> Path:
    return config_dir() / "matlab_session"


def render_server_script(sdir: Path) -> str:
    """pf_server.m: heartbeat + request loop calling pf_snapshot per request."""
    return f"""function pf_server
% generated by PipeForge — persistent snapshot server. Do not edit.
pf_s_dir = '{_mq(sdir)}';
pf_s_beat = 0;
pf_s_write(fullfile(pf_s_dir, 'ready'), 'ready');
while true
    if isfile(fullfile(pf_s_dir, 'stop'))
        delete(fullfile(pf_s_dir, 'stop'));
        break
    end
    pf_s_beat = pf_s_beat + 1;
    if mod(pf_s_beat, 40) == 1  % every ~2 s at 50 ms pause
        pf_s_write(fullfile(pf_s_dir, 'heartbeat'), num2str(pf_s_beat));
    end
    pf_s_reqs = dir(fullfile(pf_s_dir, 'request_*.json'));
    for pf_s_i = 1:numel(pf_s_reqs)
        pf_s_path = fullfile(pf_s_dir, pf_s_reqs(pf_s_i).name);
        pf_s_nonce = erase(erase(pf_s_reqs(pf_s_i).name, 'request_'), '.json');
        try
            pf_s_req = jsondecode(fileread(pf_s_path));
        catch
            pf_s_req = struct('script', '', 'setup', '', 'out', '');
        end
        delete(pf_s_path);
        try
            pf_snapshot(pf_s_req.script, pf_s_req.setup, pf_s_req.out);
        catch pf_s_err
            pf_s_doc = struct();
            pf_s_doc.error = pf_s_err.message;
            pf_s_doc.variables = {{}};
            pf_s_write(pf_s_req.out, jsonencode(pf_s_doc));
        end
        pf_s_write(fullfile(pf_s_dir, ['done_' pf_s_nonce]), 'done');
    end
    pause(0.05);
end
end

function pf_s_write(pf_s_file, pf_s_text)
pf_s_fh = fopen(pf_s_file, 'w');
fwrite(pf_s_fh, pf_s_text);
fclose(pf_s_fh);
end
"""


def server_alive() -> bool:
    """Is *some* PipeForge MATLAB server answering? (heartbeat freshness)."""
    beat = session_dir() / "heartbeat"
    try:
        return (time.time() - beat.stat().st_mtime) < HEARTBEAT_FRESH_S
    except OSError:
        return False


def request_snapshot(
    script: Path | None,
    setup: Path | None,
    timeout: float = REQUEST_TIMEOUT_S,
) -> WorkspaceSnapshot:
    """Ask the live server for a snapshot (works from any process).

    Raises MatlabUnavailable on timeout — callers fall back to batch mode.
    """
    sdir = session_dir()
    nonce = secrets.token_hex(8)
    out = sdir / f"snapshot_{nonce}.json"
    done = sdir / f"done_{nonce}"
    request = sdir / f"request_{nonce}.json"
    payload = json.dumps(
        {
            "script": str(script) if script else "",
            "setup": str(setup) if setup else "",
            "out": str(out),
        }
    )
    # atomic publish: the server must never see a half-written request
    tmp = sdir / f"pending_{nonce}.tmp"
    tmp.write_text(payload, encoding="utf-8")
    tmp.rename(request)
    deadline = time.time() + timeout
    while time.time() < deadline:
        if done.is_file():
            done.unlink(missing_ok=True)
            try:
                text = out.read_text(encoding="utf-8")
            finally:
                out.unlink(missing_ok=True)
            return WorkspaceSnapshot.from_json(text)
        time.sleep(0.05)
    request.unlink(missing_ok=True)
    raise MatlabUnavailable(
        f"warm MATLAB session did not answer within {timeout:.0f}s; falling back to batch mode"
    )


class MatlabSession:
    """Owner of the background MATLAB server process."""

    def __init__(self, config: MatlabConfig | None = None) -> None:
        self.config = config if config is not None else MatlabConfig.load()
        self._proc: subprocess.Popen[bytes] | None = None
        self._adopted = False  # using a server another process owns (do not kill)

    def is_alive(self) -> bool:
        if self._adopted:
            return server_alive()
        return self._proc is not None and self._proc.poll() is None and server_alive()

    def start(
        self,
        timeout: float = START_TIMEOUT_S,
        log: Callable[[str], None] | None = None,
    ) -> None:
        """Pay the cold start once; raises MatlabUnavailable on failure.

        If a healthy server is already answering (e.g. the GUI's warm session,
        or another PipeForge process), *adopt* it rather than launch a second
        MATLAB — two servers would fight over the same request files and burn a
        second license seat. An adopted server is never torn down by `stop()`.
        """
        if self.is_alive():
            return
        if server_alive():
            self._adopted = True
            if log:
                log("matlab session: adopting the already-running warm server")
            return
        if not fast_available(self.config):
            raise MatlabUnavailable(
                f"'{self.config.command[0]}' is not on PATH — cannot start a warm MATLAB session."
            )
        sdir = session_dir()
        sdir.mkdir(parents=True, exist_ok=True)
        for stale in ("ready", "heartbeat", "stop"):
            (sdir / stale).unlink(missing_ok=True)
        for leftover in sdir.glob("request_*.json"):
            leftover.unlink(missing_ok=True)
        (sdir / "pf_server.m").write_text(render_server_script(sdir), encoding="utf-8")
        (sdir / "pf_snapshot.m").write_text(render_snapshot_function(), encoding="utf-8")
        cmd = [*self.config.command, "-batch", f"cd('{_mq(sdir)}'); pf_server"]
        if log:
            log("matlab session: starting — " + " ".join(cmd))
        try:
            self._proc = subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        except OSError as exc:
            raise MatlabUnavailable(f"cannot launch the MATLAB session: {exc}") from exc
        deadline = time.time() + timeout
        ready = sdir / "ready"
        while time.time() < deadline:
            if ready.is_file():
                if log:
                    log("matlab session: warm — snapshots are now near-instant")
                return
            if self._proc.poll() is not None:
                break
            time.sleep(0.2)
        self.stop()
        raise MatlabUnavailable(
            "the MATLAB session did not become ready in time; manual (batch) refresh still works"
        )

    def stop(self) -> None:
        """Graceful stop (server exits its loop), then terminate.

        A server we merely *adopted* (started by another process) is left
        running — its owner controls its lifecycle.
        """
        if self._adopted:
            self._adopted = False
            return
        sdir = session_dir()
        with contextlib.suppress(OSError):
            (sdir / "stop").write_text("stop", encoding="utf-8")
        if self._proc is not None:
            with contextlib.suppress(subprocess.TimeoutExpired):
                self._proc.wait(timeout=5)
            if self._proc.poll() is None:
                self._proc.terminate()
                with contextlib.suppress(subprocess.TimeoutExpired):
                    self._proc.wait(timeout=5)
                if self._proc.poll() is None:
                    self._proc.kill()
            self._proc = None
        for marker in ("ready", "heartbeat"):
            (sdir / marker).unlink(missing_ok=True)
