// Generated by PipeForge from normalize3d.m
// fixedp WIDTH=16 SCALE=12 — critical path 48 cycles
// Do not edit: regenerate with `pipeforge-cli codegen`.

`include "macros.svh"

module gen_normalize3d
  (
  fixedp g,

  input valid_0,
  input [g.WIDTH-1:0] x_0,
  input [g.WIDTH-1:0] y_0,
  input [g.WIDTH-1:0] z_0,

  output valid_N,
  output [g.WIDTH-1:0] ux_N,
  output [g.WIDTH-1:0] uy_N,
  output [g.WIDTH-1:0] uz_N
  );

logic [g.WIDTH-1:0] t1_4;
logic [g.WIDTH-1:0] t2_4;
logic [g.WIDTH-1:0] t3_5;
logic [g.WIDTH-1:0] t4_4;
logic [g.WIDTH-1:0] n2_6;
logic [g.WIDTH-1:0] t4_5;
logic [g.WIDTH-1:0] n_20;
logic [g.WIDTH-1:0] ux_48;
logic [g.WIDTH-1:0] x_20;
logic [g.WIDTH-1:0] uy_48;
logic [g.WIDTH-1:0] y_20;
logic [g.WIDTH-1:0] uz_48;
logic [g.WIDTH-1:0] z_20;
logic valid_48;

// stage 4: (x .* x)
elem_smul i_elem_smul_t1_4
  (
    .g (g),
    .a (x_0),
    .b (x_0),
    .f (t1_4)
  );

// stage 4: (y .* y)
elem_smul i_elem_smul_t2_4
  (
    .g (g),
    .a (y_0),
    .b (y_0),
    .f (t2_4)
  );

// stage 5: ((x .* x) + (y .* y))
matadd i_matadd_t3_5
  (
    .g (g),
    .a (t1_4),
    .b (t2_4),
    .f (t3_5)
  );

// stage 4: (z .* z)
elem_smul i_elem_smul_t4_4
  (
    .g (g),
    .a (z_0),
    .b (z_0),
    .f (t4_4)
  );

pipe #(.WIDTH($bits(t4_4)), .DELAY(1)) i_pipe_t4_5
  (
    .g (g), .i (t4_4), .o (t4_5)
  );

// stage 6: (((x .* x) + (y .* y)) + (z .* z))
matadd i_matadd_n2_6
  (
    .g (g),
    .a (t3_5),
    .b (t4_5),
    .f (n2_6)
  );

// stage 20: sqrt(n2)
elem_usqrt i_elem_usqrt_n_20
  (
    .g (g),
    .a (n2_6),
    .f (n_20)
  );

pipe #(.WIDTH($bits(x_0)), .DELAY(20)) i_pipe_x_20
  (
    .g (g), .i (x_0), .o (x_20)
  );

// stage 48: (x ./ n)
elem_sdiv i_elem_sdiv_ux_48
  (
    .g (g),
    .a (x_20),
    .b (n_20),
    .f (ux_48)
  );

pipe #(.WIDTH($bits(y_0)), .DELAY(20)) i_pipe_y_20
  (
    .g (g), .i (y_0), .o (y_20)
  );

// stage 48: (y ./ n)
elem_sdiv i_elem_sdiv_uy_48
  (
    .g (g),
    .a (y_20),
    .b (n_20),
    .f (uy_48)
  );

pipe #(.WIDTH($bits(z_0)), .DELAY(20)) i_pipe_z_20
  (
    .g (g), .i (z_0), .o (z_20)
  );

// stage 48: (z ./ n)
elem_sdiv i_elem_sdiv_uz_48
  (
    .g (g),
    .a (z_20),
    .b (n_20),
    .f (uz_48)
  );

valid #(.WIDTH(1), .DELAY(48)) i_valid_valid_48
  (
    .g (g), .i (valid_0), .o (valid_48)
  );
assign valid_N = valid_48;
assign ux_N = ux_48;
assign uy_N = uy_48;
assign uz_N = uz_48;

endmodule
