// Generated by PipeForge from rootsqr.m
// fixedp WIDTH=16 SCALE=12 — critical path 19 cycles
// Do not edit: regenerate with `pipeforge-cli codegen`.

`include "macros.svh"

module gen_rootsqr
  (
  fixedp g,

  input valid_0,
  input [g.WIDTH-1:0] v_0,

  output valid_N,
  output [g.WIDTH-1:0] m_N,
  output [g.WIDTH-1:0] r_N
  );

logic [g.WIDTH-1:0] m_19;
logic [g.WIDTH-1:0] d_5;
logic [g.WIDTH-1:0] r_19;
logic valid_19;

// stage 19: norm(v)
rootsqr i_rootsqr_m_19
  (
    .g (g),
    .a (v_0),
    .f (m_19)
  );

// stage 5: sumsqr(v)
sumsqr i_sumsqr_d_5
  (
    .g (g),
    .a (v_0),
    .f (d_5)
  );

// stage 19: sqrt(d)
elem_usqrt i_elem_usqrt_r_19
  (
    .g (g),
    .a (d_5),
    .f (r_19)
  );

valid #(.WIDTH(1), .DELAY(19)) i_valid_valid_19
  (
    .g (g), .i (valid_0), .o (valid_19)
  );
assign valid_N = valid_19;
assign m_N = m_19;
assign r_N = r_19;

endmodule
