// Generated by PipeForge from sample.m
// fixedp WIDTH=16 SCALE=12 — critical path 5 cycles
// Do not edit: regenerate with `pipeforge-cli codegen`.

`include "macros.svh"

module gen_sample
  (
  fixedp g,

  input valid_0,
  input [g.WIDTH-1:0] a_0,
  input [g.WIDTH-1:0] b_0,
  input [g.WIDTH-1:0] c_0,

  output valid_N,
  output [g.WIDTH-1:0] y_N
  );

logic [g.WIDTH-1:0] prod_4;
logic [g.WIDTH-1:0] y_5;
logic [g.WIDTH-1:0] c_4;
logic valid_5;

// stage 4: (a .* b)
elem_smul i_elem_smul_prod_4
  (
    .g (g),
    .a (a_0),
    .b (b_0),
    .f (prod_4)
  );

pipe #(.WIDTH($bits(c_0)), .DELAY(4)) i_pipe_c_4
  (
    .g (g), .i (c_0), .o (c_4)
  );

// stage 5: (prod + c)
matadd i_matadd_y_5
  (
    .g (g),
    .a (prod_4),
    .b (c_4),
    .f (y_5)
  );

valid #(.WIDTH(1), .DELAY(5)) i_valid_valid_5
  (
    .g (g), .i (valid_0), .o (valid_5)
  );
assign valid_N = valid_5;
assign y_N = y_5;

endmodule
