"""Verilator --lint-only as an additional lint backend (SL-7).

PipeForge's own linter checks nkMatlib *conventions*; Verilator's linter
catches general SystemVerilog problems (width mismatches, latch inference,
combinational loops). Findings are normalized to the same LintFinding shape
so both sets render in one table. Missing Verilator degrades to an
actionable message.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import tempfile
from pathlib import Path

from pipeforge.core.svlint.checks import LintFinding


class VerilatorUnavailable(RuntimeError):
    pass


#: `%Warning-WIDTHEXPAND: file.sv:12:5: message` (column optional)
_MSG_RE = re.compile(
    r"^%(?P<sev>Warning|Error)(?:-(?P<code>[A-Z0-9_]+))?:\s*"
    r"(?P<file>[^:]+):(?P<line>\d+):(?:(?P<col>\d+):)?\s*(?P<msg>.*)$"
)

#: codes that are noise for nkMatlib-style code (interface-heavy, generated)
_SUPPRESSED = ("DECLFILENAME", "UNUSEDSIGNAL", "UNUSEDPARAM", "VARHIDDEN")


def parse_verilator_output(log: str, for_file: str) -> list[LintFinding]:
    """Normalize Verilator messages for one file into LintFindings (testable)."""
    findings: list[LintFinding] = []
    for raw in log.splitlines():
        m = _MSG_RE.match(raw.strip())
        if m is None:
            continue
        code = m.group("code") or m.group("sev").upper()
        if code in _SUPPRESSED:
            continue
        if Path(m.group("file")).name != Path(for_file).name:
            continue  # messages about includes/library files are not this file's
        findings.append(
            LintFinding(
                check=f"verilator-{code}",
                line=int(m.group("line")),
                message=m.group("msg").strip(),
                fix="see `verilator --help` / the Verilator manual for this code",
            )
        )
    return findings


def render_lint_top(sv_text: str, width: int, scale: int) -> str | None:
    """A throwaway top that connects the DUT's fixedp interface for lint.

    Verilator refuses to lint a module whose interface port has no connected
    parent; this synthesizes the same minimal harness an engineer would write
    by hand. Returns None when the file has no fixedp-style interface port
    (then the DUT lints stand-alone).
    """
    from pipeforge.core.svlint.model import is_valid_signal
    from pipeforge.core.svlint.parse import parse_sv

    module, _backend = parse_sv(sv_text)
    if not module.has_fixedp or not module.name:
        return None
    decls: list[str] = []
    conns: list[str] = ["    .g (g)"]
    for port in module.ports:
        if port.direction == "interface":
            continue
        bits = "" if is_valid_signal(port.name) else f"[{width - 1}:0] "
        decls.append(f"  logic {bits}w_{port.name};")
        conns.append(f"    .{port.name} (w_{port.name})")
    body = "\n".join(decls)
    conn = ",\n".join(conns)
    return f"""// generated by pipeforge lint --verilator — throwaway interface harness
module pf_lint_top;
  logic clk, reset;
  fixedp #(.WIDTH({width}), .SCALE({scale})) g (.clk (clk), .reset (reset));
{body}
  {module.name} dut
  (
{conn}
  );
endmodule
"""


def verilator_lint(
    sv_path: Path,
    include_dirs: list[Path] | None = None,
    extra_sources: list[Path] | None = None,
    timeout: int = 120,
    width: int = 16,
    scale: int = 12,
) -> list[LintFinding]:
    """Run `verilator --lint-only -Wall` and normalize the findings (SL-7)."""
    if shutil.which("verilator") is None:
        raise VerilatorUnavailable(
            "the Verilator lint backend needs Verilator "
            "(install: pacman -S verilator / apt install verilator)."
        )
    # Verilator lazily resolves *instantiated* modules from -I dirs, but an
    # interface that appears only as a port type (nkMatlib's `fixedp g`) never
    # triggers that lookup — feed interface definitions explicitly.
    iface_files: list[Path] = []
    for d in include_dirs or []:
        for f in sorted(d.glob("*.sv")):
            try:
                head = f.read_text(encoding="utf-8", errors="replace")[:4096]
            except OSError:
                continue
            if "interface " in head:
                iface_files.append(f)
    top_args: list[str] = []
    tmp: tempfile.TemporaryDirectory[str] | None = None
    try:
        sv_text = sv_path.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        raise VerilatorUnavailable(f"cannot read {sv_path}: {exc}") from exc
    harness = render_lint_top(sv_text, width, scale)
    if harness is not None and iface_files:
        tmp = tempfile.TemporaryDirectory(prefix="pipeforge_vlint_")
        top_file = Path(tmp.name) / "pf_lint_top.sv"
        top_file.write_text(harness, encoding="utf-8")
        top_args = [str(top_file), "--top-module", "pf_lint_top"]
    cmd = [
        "verilator",
        "--lint-only",
        "-Wall",
        "-Wno-fatal",
        *[f"-I{d.resolve()}" for d in (include_dirs or [])],
        *[str(f.resolve()) for f in iface_files],
        str(sv_path.resolve()),
        *[str(s.resolve()) for s in (extra_sources or [])],
        *top_args,
    ]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    except (OSError, subprocess.SubprocessError) as exc:
        raise VerilatorUnavailable(f"verilator failed to run: {exc}") from exc
    finally:
        if tmp is not None:
            tmp.cleanup()
    return parse_verilator_output(proc.stdout + proc.stderr, str(sv_path))
