"""RTM gate check (§9): no P0 requirement without at least one passing test.

Reads docs/rtm.csv (regenerated by `pytest --rtm-out=docs/rtm.csv`).
Tool-gated requirements may be 'skipped' locally; they execute in the CI
verify-with-tools job.
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

#: P0 requirements with automated-test verification (SRS sections 4-6).
P0_TESTED = [
    "FE-1",
    "FE-2",
    "FE-3",
    "FE-4",
    "AU-1",
    "AU-2",
    "AU-3",
    "AU-4",
    "AU-5",
    "FX-1",
    "FX-2",
    "FX-3",
    "FX-4",
    "FX-5",
    "CS-1",
    "CS-2",
    "CS-3",
    "CS-4",
    "BI-1",
    "BI-2",
    "SL-1",
    "SL-2",
    "SL-3",
    "CG-1",
    "CG-2",
    "CG-3",
    "CG-4",
    "RP-1",
    "DSE-1",
    "DSE-2",
    "VZ-1",
    "VZ-2",
    "VZ-3",
    "UI-1",
    "UI-2",
    "UI-4",
    "UI-6",
    "TH-1",
    "TH-2",
    "TH-3",
    "TH-4",
    "TH-5",
    "NF-1",
    "NF-4",
    # --- SCS v1.1 Phase A (P0) ---
    "AR-1",
    "AR-2",
    "AR-3",
    "AR-4",
    "AR-5",
    "WS-1",
    "WS-2",
    # --- SCS v1.1 Phase B (P0) ---
    "MP-1",
    "MP-2",
    "MP-6",
    # --- SCS v1.1 Phase C (P0) ---
    "WS-3",
    "CS-5",
    "CS-6",
]

#: Requirements whose tests legitimately skip without external tools (§8.2).
#: AR-4 also has a tool-free unit test, so it passes even when Verilator is absent.
TOOL_GATED = {"CS-4", "CG-3"}


def main() -> int:
    rtm = Path(__file__).parent.parent / "docs" / "rtm.csv"
    if not rtm.is_file():
        print("docs/rtm.csv missing — run: pytest --rtm-out=docs/rtm.csv", file=sys.stderr)
        return 2
    status: dict[str, set[str]] = {}
    with rtm.open(encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            status.setdefault(row["requirement"], set()).add(row["status"])
    missing = []
    for req in P0_TESTED:
        outcomes = status.get(req, set())
        if "passed" in outcomes:
            continue
        if req in TOOL_GATED and "skipped" in outcomes:
            continue  # executes in the CI tools job
        missing.append(req)
    if missing:
        print(f"P0 requirements without a passing test: {missing}", file=sys.stderr)
        return 1
    covered = sum(1 for r in P0_TESTED if "passed" in status.get(r, set()))
    print(
        f"RTM gate OK: {covered}/{len(P0_TESTED)} P0 requirements passing here, "
        f"{len(TOOL_GATED)} tool-gated (CI)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
