"""AXI-Stream wrapper generation (AX-1).

nkMatlib pipelines cannot stall: once `valid_0` is asserted a result *will*
emerge `latency` cycles later. The rest of an FPGA design usually speaks
AXI-Stream (tvalid/tready), so this wrapper makes the two meet safely:

* a **credit counter** admits a new beat only when a slot in the output FIFO
  is guaranteed to be free when the result lands (in-flight results count
  against the credit), and
* an **output FIFO** (depth = latency rounded up to a power of two, +4 slack)
  absorbs results while the consumer back-pressures.

Throughput remains 1 beat/clock when the consumer keeps up. All inputs pack
into ``s_axis_tdata`` (input 0 in the lowest lanes); outputs likewise.
"""

from __future__ import annotations

from pipeforge.core.audit.engine import Audit
from pipeforge.core.frontend.dag import port_name


def generate_axis_wrapper(audit: Audit, module_name: str) -> str:
    """Emit `<module>_axis`, an AXI-Stream wrapper around the generated core."""
    inputs = [port_name(n.label) for n in audit.dag.inputs()]
    outputs = [n.signal for n in audit.dag.outputs() if n.signal]
    if not outputs:
        raise ValueError("the DAG has no outputs; nothing to wrap")
    w = audit.cm.width
    scale = audit.cm.scale
    latency = audit.total_latency
    depth = 1
    while depth < latency + 4:
        depth *= 2
    n_in, n_out = len(inputs), len(outputs)

    in_conns = ",\n".join(
        f"      .{name}_0 (s_axis_tdata[{i} * WIDTH +: WIDTH])" for i, name in enumerate(inputs)
    )
    out_decls = "\n".join(f"  logic [WIDTH-1:0] {name}_N;" for name in outputs)
    out_conns = ",\n".join(f"      .{name}_N ({name}_N)" for name in outputs)
    result_pack = ", ".join(f"{name}_N" for name in reversed(outputs))
    in_map = ", ".join(f"[{i}]={name}" for i, name in enumerate(inputs))
    out_map = ", ".join(f"[{i}]={name}" for i, name in enumerate(outputs))

    return f"""// Generated by PipeForge from {audit.filename} — AXI-Stream wrapper (AX-1).
// s_axis_tdata lanes: {in_map}   ·   m_axis_tdata lanes: {out_map}
// The nkMatlib core cannot stall; a credit counter admits a beat only when
// the output FIFO is guaranteed a free slot when its result lands.
// Do not edit: regenerate with `pipeforge-cli codegen --axis`.

`include "macros.svh"

module {module_name}_axis
  #(
    parameter WIDTH = {w},
    parameter SCALE = {scale}
  )
  (
  input                          aclk,
  input                          aresetn,

  input                          s_axis_tvalid,
  output                         s_axis_tready,
  input  [{n_in} * WIDTH - 1:0]  s_axis_tdata,

  output                         m_axis_tvalid,
  input                          m_axis_tready,
  output [{n_out} * WIDTH - 1:0] m_axis_tdata
  );

localparam DEPTH = {depth};        // >= latency ({latency}) + 4, power of two
localparam PTR_BITS = $clog2(DEPTH);

fixedp #(.WIDTH(WIDTH), .SCALE(SCALE)) g (.clk (aclk), .reset (!aresetn));

// -- the pipeline core ----------------------------------------------------
logic valid_N;
{out_decls}

wire accept = s_axis_tvalid && s_axis_tready;

{module_name} i_core
  (
    .g (g),
    .valid_0 (accept),
{in_conns},
    .valid_N (valid_N),
{out_conns}
  );

// -- output FIFO (results land here unconditionally; never overflows by the
//    credit invariant below) -----------------------------------------------
logic [{n_out} * WIDTH - 1:0] fifo_mem [0:DEPTH - 1];
logic [PTR_BITS - 1:0] wr_ptr, rd_ptr;
logic [PTR_BITS:0] count;

wire release_beat = m_axis_tvalid && m_axis_tready;

always @(posedge aclk) begin
  if (!aresetn) begin
    wr_ptr <= '0;
    rd_ptr <= '0;
    count <= '0;
  end else begin
    if (valid_N) begin
      fifo_mem[wr_ptr] <= {{ {result_pack} }};
      wr_ptr <= wr_ptr + 1'b1;
    end
    if (release_beat)
      rd_ptr <= rd_ptr + 1'b1;
    count <= count + (PTR_BITS + 1)'(valid_N) - (PTR_BITS + 1)'(release_beat);
  end
end

assign m_axis_tvalid = (count != 0);
assign m_axis_tdata = fifo_mem[rd_ptr];

// -- credit counter: free FIFO slots not yet claimed by an in-flight beat --
logic [PTR_BITS:0] credits;

always @(posedge aclk) begin
  if (!aresetn)
    credits <= DEPTH[PTR_BITS:0];
  else
    credits <= credits - (PTR_BITS + 1)'(accept) + (PTR_BITS + 1)'(release_beat);
end

assign s_axis_tready = aresetn && (credits != 0);

endmodule
"""
